##端口设置
server:
  port: 80
###注册 中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka/
###网关名称
spring:
  application:
    name: alucard-zuul

###配置网关反向代理
zuul:
  routes:
    api-a:
      path: /api-member/**
      serviceId: alucard-member
    api-b:
      path: /api-order/**
      serviceId: alucard-order
