##服务端口
server:
  port: 8102
###服务名称,同时也是注册到eureka的名称
spring:
  application:
    name: alucard-member
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka
    ###注册到eureka
    register-with-eureka: true
    ###是否需要从eureka上获取注册信息
    fetch-registry: true
    registry-fetch-interval-seconds: 30
  # 心跳检测检测与续约时间
  # 测试时将值设置设置小些，保证服务关闭后注册中心能及时踢出服务
  instance:
    ###Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则）
    lease-expiration-duration-in-seconds: 2
    ####Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己）
    lease-renewal-interval-in-seconds: 1
swagger:
  base-package: com.alucard.controller