server:
  port: 8090
spring:
  ####\u6574\u5408\u6570\u636E\u5E93\u5C42
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password:
    # druid \u8FDE\u63A5\u6C60
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
